"""Baseline schema — the tables as first created by ``cnms-fom init-db``.

Exists so a database built before Alembic was introduced has a revision to
be stamped at: ``alembic stamp 0001`` then ``alembic upgrade head``. A fresh
database just runs ``alembic upgrade head`` and gets both revisions.

Original message: baseline schema

Revision ID: 0001
Revises:
Created: 2026-09-17 18:57:57.316072
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('eligible_material_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('permutation_b', sa.Integer(), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('technique', sa.Enum('MBE', 'PLD', 'ALD', 'SPUTTERING', 'CVD', 'SOLUTION', 'CNMS_USER_DOC', 'OTHER', name='synthesis_technique'), nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('doc_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_sha256')
    )
    op.create_table('fom_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('application', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalization', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('floor_eps', sa.Float(), nullable=False),
    sa.Column('bounds_basis', sa.Text(), nullable=True),
    sa.Column('eligible_set_query', sa.Text(), nullable=True),
    sa.Column('n_materials_in_bounds', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_fom_name_version')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('technique', sa.Enum('MBE', 'PLD', 'ALD', 'SPUTTERING', 'CVD', 'SOLUTION', 'CNMS_USER_DOC', 'OTHER', name='synthesis_technique'), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula', sa.String(length=128), nullable=False),
    sa.Column('formula_reduced', sa.String(length=128), nullable=False),
    sa.Column('polymorph', sa.String(length=128), nullable=False),
    sa.Column('space_group_symbol', sa.String(length=32), nullable=True),
    sa.Column('space_group_number', sa.Integer(), nullable=True),
    sa.Column('specimen_form', sa.Enum('BULK_SINGLE_CRYSTAL', 'CERAMIC', 'AMORPHOUS_FILM', 'CRYSTALLINE_FILM', 'COMPUTATIONAL', 'OTHER', name='specimen_form'), nullable=False),
    sa.Column('source_database', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formula_reduced', 'polymorph', 'specimen_form', name='uq_material_identity')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_formula', ['formula_reduced'], unique=False)

    op.create_table('bo_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('fom_definition_id', sa.Integer(), nullable=True),
    sa.Column('search_space', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('acquisition', sa.String(length=32), nullable=False),
    sa.Column('objective_sense', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fom_definition_id'], ['fom_definitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.Enum('SS', 'SP', 'PP', 'FF', 'SF', name='correlation_block'), nullable=False),
    sa.Column('x_key', sa.String(length=64), nullable=False),
    sa.Column('y_key', sa.String(length=64), nullable=False),
    sa.Column('x_transform', sa.Enum('NONE', 'LOG10', name='transform'), nullable=False),
    sa.Column('y_transform', sa.Enum('NONE', 'LOG10', name='transform'), nullable=False),
    sa.Column('pearson_r', sa.Float(), nullable=True),
    sa.Column('spearman_rho', sa.Float(), nullable=True),
    sa.Column('n_complete', sa.Integer(), nullable=False),
    sa.Column('p_permutation', sa.Float(), nullable=True),
    sa.Column('q_fdr', sa.Float(), nullable=True),
    sa.Column('predicted_sign', sa.String(length=16), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('SUPPORTS', 'CONTRADICTS', 'INCONCLUSIVE', name='hypothesis_outcome'), nullable=True),
    sa.Column('material_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlation_results', schema=None) as batch_op:
        batch_op.create_index('ix_corr_run_block', ['run_id', 'block'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlation_results_run_id'), ['run_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('n_tokens', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_position')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('fom_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('fom_definition_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('log_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SCORED', 'NOT_SCORED', 'ILLUSTRATIVE', name='score_status'), nullable=False),
    sa.Column('missing_inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uses_modeled_inputs', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fom_definition_id'], ['fom_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'fom_definition_id', 'run_id', name='uq_fom_score')
    )
    with op.batch_alter_table('fom_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fom_scores_fom_definition_id'), ['fom_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fom_scores_material_id'), ['material_id'], unique=False)

    op.create_table('mediation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('fom_definition_id', sa.Integer(), nullable=True),
    sa.Column('descriptor_key', sa.String(length=64), nullable=False),
    sa.Column('application', sa.String(length=64), nullable=False),
    sa.Column('mediated_effect', sa.Float(), nullable=False),
    sa.Column('contributions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dominant_property', sa.String(length=64), nullable=True),
    sa.Column('sensitivity_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fom_definition_id'], ['fom_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mediation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mediation_results_run_id'), ['run_id'], unique=False)

    op.create_table('structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.Text(), nullable=False),
    sa.Column('n_sites', sa.Integer(), nullable=True),
    sa.Column('formula_units_per_cell', sa.Integer(), nullable=True),
    sa.Column('volume_ang3', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('xc_functional', sa.String(length=64), nullable=True),
    sa.Column('provenance_tier', sa.Enum('MEASURED', 'CALCULATED', 'MODELED', 'UNAVAILABLE', name='provenance_tier'), nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structures_material_id'), ['material_id'], unique=False)

    op.create_table('bo_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bo_run_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acquisition_value', sa.Float(), nullable=True),
    sa.Column('predicted_mean', sa.Float(), nullable=True),
    sa.Column('predicted_std', sa.Float(), nullable=True),
    sa.Column('batch_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bo_run_id'], ['bo_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bo_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bo_suggestions_bo_run_id'), ['bo_run_id'], unique=False)

    op.create_table('descriptor_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('descriptor_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=32), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('xc_functional', sa.String(length=64), nullable=True),
    sa.Column('provenance_tier', sa.Enum('MEASURED', 'CALCULATED', 'MODELED', 'UNAVAILABLE', name='provenance_tier'), nullable=False),
    sa.Column('reduction_rule', sa.String(length=64), nullable=True),
    sa.Column('direction_hint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'descriptor_key', 'method', name='uq_descriptor_value')
    )
    with op.batch_alter_table('descriptor_values', schema=None) as batch_op:
        batch_op.create_index('ix_descriptor_key', ['descriptor_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_descriptor_values_material_id'), ['material_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('bo_suggestion_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('sample_id', sa.String(length=64), nullable=True),
    sa.Column('recipe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bo_suggestion_id'], ['bo_suggestions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('bo_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bo_run_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('objective_noise', sa.Float(), nullable=True),
    sa.Column('fom_score_id', sa.Integer(), nullable=True),
    sa.Column('is_feasible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bo_run_id'], ['bo_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fom_score_id'], ['fom_scores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bo_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bo_observations_bo_run_id'), ['bo_run_id'], unique=False)

    op.create_table('property_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('property_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=32), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('tensor_component', sa.String(length=16), nullable=True),
    sa.Column('direction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reduction_rule', sa.String(length=64), nullable=True),
    sa.Column('temperature_k', sa.Float(), nullable=True),
    sa.Column('frequency_hz', sa.Float(), nullable=True),
    sa.Column('field_amplitude_v_per_cm', sa.Float(), nullable=True),
    sa.Column('thickness_nm', sa.Float(), nullable=True),
    sa.Column('electrode', sa.String(length=64), nullable=True),
    sa.Column('substrate', sa.String(length=64), nullable=True),
    sa.Column('interface', sa.String(length=128), nullable=True),
    sa.Column('area_cm2', sa.Float(), nullable=True),
    sa.Column('failure_criterion', sa.String(length=128), nullable=True),
    sa.Column('processing_route', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('software', sa.String(length=64), nullable=True),
    sa.Column('xc_functional', sa.String(length=64), nullable=True),
    sa.Column('pseudopotential', sa.String(length=128), nullable=True),
    sa.Column('convergence', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('database_identifier', sa.String(length=128), nullable=True),
    sa.Column('source_locator', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_tier', sa.Enum('MEASURED', 'CALCULATED', 'MODELED', 'UNAVAILABLE', name='provenance_tier'), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_values', schema=None) as batch_op:
        batch_op.create_index('ix_property_key', ['property_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_values_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_values_material_id'))
        batch_op.drop_index('ix_property_key')

    op.drop_table('property_values')
    with op.batch_alter_table('bo_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bo_observations_bo_run_id'))

    op.drop_table('bo_observations')
    op.drop_table('experiments')
    with op.batch_alter_table('descriptor_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_descriptor_values_material_id'))
        batch_op.drop_index('ix_descriptor_key')

    op.drop_table('descriptor_values')
    with op.batch_alter_table('bo_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bo_suggestions_bo_run_id'))

    op.drop_table('bo_suggestions')
    with op.batch_alter_table('structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structures_material_id'))

    op.drop_table('structures')
    with op.batch_alter_table('mediation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mediation_results_run_id'))

    op.drop_table('mediation_results')
    with op.batch_alter_table('fom_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fom_scores_material_id'))
        batch_op.drop_index(batch_op.f('ix_fom_scores_fom_definition_id'))

    op.drop_table('fom_scores')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('correlation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlation_results_run_id'))
        batch_op.drop_index('ix_corr_run_block')

    op.drop_table('correlation_results')
    op.drop_table('bo_runs')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_formula')

    op.drop_table('materials')
    op.drop_table('instruments')
    op.drop_table('fom_definitions')
    op.drop_table('documents')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
